#!/usr/bin/python3

print("<!DOCTYPE html>")
print("<html lang='en'>")
print("<head>")
print("<meta charset='UTF-8'>")
print("<title>Webserv - Random Image</title>")
print("</head>")
print("<body>")
print("<h1>Random Image</h1>")
print("<img src=\"https://picsum.photos/500/500\">")
print("<hr>")
print("<button onclick='document.location.reload()'> Random </button>")
print("<style>")
print("button {")
print("background-color: #4CAF50;")
print("border: none;")
print("color: white;")
print("padding: 15px 32px;")
print("text-align: center;")
print("text-decoration: none;")
print("display: inline-block;")
print("font-size: 16px;")
print("margin: 4px 2px;")
print("cursor: pointer;")
print("}")
print("</style>")

print("</body>")
print("</html>")
